# Week 0 - Elementary of PyTorch

In [1]:
import torch
import numpy as np

In [4]:
# Everything in PyTorch is based on Tensor operations.
# A tensor can have different dimensions: scalar, vector, matrix, tensor

# torch.empty(size): uninitialized
x = torch.empty(1)  # scalar
print("Scalar Tensor (unintialized):")
print(x)

x = torch.empty(3)  # vector, 1D
print("\nVector Tensor (unitialized):")
print(x)

x = torch.empty(2, 3)  # matrix, 2D
print("\nMatrix Tensor (unitialized):")
print(x)

x = torch.empty(2, 2, 3)  # tensor, 3 dimensions
print("\nTensor (3D) Tensor (unintialized):")
print(x)

x = torch.empty(2, 2, 2, 3)  # tensor, 4 dimensions
print("\nTensor (4D) Tensor (unintioalized):")
print(x)

Scalar Tensor (unintialized):
tensor([3.6083e-09])

Vector Tensor (unitialized):
tensor([-1.2900e-26,  3.2398e-41, -1.2868e-26])

Matrix Tensor (unitialized):
tensor([[-4.5331e-02,  4.5769e-41, -1.2305e-26],
        [ 3.2398e-41,  4.4842e-44,  0.0000e+00]])

Tensor (3D) Tensor (unintialized):
tensor([[[-1.2901e-26,  3.2398e-41, -1.2353e-26],
         [ 3.2398e-41, -1.0635e+08,  4.5768e-41]],

        [[-1.0635e+08,  4.5768e-41, -1.0635e+08],
         [ 4.5768e-41, -1.0635e+08,  4.5768e-41]]])

Tensor (4D) Tensor (unintioalized):
tensor([[[[-4.5332e-02,  4.5769e-41, -1.2818e-26],
          [ 3.2398e-41,  0.0000e+00,  1.0878e-03]],

         [[ 0.0000e+00,  1.6043e-05,  0.0000e+00],
          [ 1.9169e+01,  0.0000e+00,  1.7154e-05]]],


        [[[ 0.0000e+00,  1.9169e+01,  0.0000e+00],
          [ 1.7154e-05,  0.0000e+00,  1.9169e+01]],

         [[ 0.0000e+00,  1.7154e-05,  0.0000e+00],
          [ 1.9169e+01,  0.0000e+00,  1.7154e-05]]]])


## Create tensor with random, zeros and ones

In [6]:
# torch.rand(size) - random numbers [0, 1]
x = torch.rand(5, 3)
print("Random Tensor (Uniform Distribution):")
print(x)

# torch.zeros(size) - fill with 0
x = torch.zeros(5, 3)
print("\nTensor Filled with Zeros:")
print(x)

# torch.ones(size) - fill with 1
x = torch.ones(5, 3)
print("\nTensor Filled with Ones:")
print(x)

Random Tensor (Uniform Distribution):
tensor([[0.5112, 0.6407, 0.7435],
        [0.2742, 0.6684, 0.8683],
        [0.7569, 0.4368, 0.6171],
        [0.6059, 0.2615, 0.9390],
        [0.4628, 0.5029, 0.9599]])

Tensor Filled with Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Tensor Filled with Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


## Check Size and Data type

In [7]:
# check size
print("Size of Tensor:")
print(x.size())

# check data type
print("\nData Type of Tensor:")
print(x.dtype)

Size of Tensor:
torch.Size([5, 3])

Data Type of Tensor:
torch.float32


In [9]:
# specify types, float32 default. Convert type in other type
x = torch.zeros(5, 3, dtype=torch.float16)
print("Tensor with Specified Data Type (float16):")
print(x)

# check type
print("\nData Type of Tensor (after specifying):")
print(x.dtype)

Tensor with Specified Data Type (float16):
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)

Data Type of Tensor (after specifying):
torch.float16


In [15]:
# construct from data
x = torch.tensor([5.5, 3], dtype=torch.float16)
print("Create our Tensor:", x)

print("\nTensor Constructed from Data:")
print(x.size())

Create our Tensor: tensor([5.5000, 3.0000], dtype=torch.float16)

Tensor Constructed from Data:
torch.Size([2])


## Set requires_grad Argument in tensor



In [16]:
# requires_grad argument
# This will tell PyTorch that it will need to calculate the gradients for this tensor
# Later in your optimization steps
# i. e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


## Operations in PyTorch

In [21]:
# Operations
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print(y)
print(x)

# elemetwise addition
z = x + y
print("\nElement-wise Addition:")
print(z)

# in-place addition, everything with a trailing underscore is an inplace operations
# i.e. it will modifi the variable
# y.add_(x)

# substraction
z = x - y
print("\nSubtraction:")
print(z)

# multiplication
z = x * y
print("\nMultiplication:")
print(z)

# division
z = x / y
print("\nDivision:")
print(z)

tensor([[0.9923, 0.9269],
        [0.6291, 0.8761]])
tensor([[0.4957, 0.3685],
        [0.9491, 0.2639]])

Element-wise Addition:
tensor([[1.4880, 1.2953],
        [1.5782, 1.1400]])

Subtraction:
tensor([[-0.4966, -0.5584],
        [ 0.3199, -0.6121]])

Multiplication:
tensor([[0.4918, 0.3415],
        [0.5971, 0.2312]])

Division:
tensor([[0.4995, 0.3976],
        [1.5085, 0.3013]])


## Slicing and Get item in tensor

In [22]:
# Slicing
x = torch.rand(5, 3)
print("Sliced Tensor:")
print(x)

print("\nSliced Column:")
print(x[:, 0])  # all rows, column 0

print("\nSliced Row:")
print(x[1, :])  # row 1, all columns

print("\nSliced Element:")
print(x[1, 1])  # element at 1, 1

# Get the actual value if only 1 elemt in your tensot
print("\nValue of Single Element:")
print(x[1, 1].item())

Sliced Tensor:
tensor([[0.8265, 0.9137, 0.4298],
        [0.9670, 0.1149, 0.6236],
        [0.0266, 0.9343, 0.7912],
        [0.6183, 0.5405, 0.0997],
        [0.9072, 0.9769, 0.2382]])

Sliced Column:
tensor([0.8265, 0.9670, 0.0266, 0.6183, 0.9072])

Sliced Row:
tensor([0.9670, 0.1149, 0.6236])

Sliced Element:
tensor(0.1149)

Value of Single Element:
0.11494940519332886


## Reshaping size tensor for compatibility with other tensors or neural network layers

In [27]:
# Reshape with torch.view()
x = torch.randn(4, 4)
print(x)

y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1, PyTorch will automatically determine the necesseary size

print("\nReshaping Tensors:")
print(x.size(), y.size(), z.size())

print("\nShows the y, z tensor:")
print(y)
print(z)

tensor([[ 0.9959,  0.4080, -0.7122,  2.5993],
        [-0.1235, -1.9314, -0.2966, -2.2324],
        [-0.2596, -0.2073,  0.3111, -0.5772],
        [-1.3707, -1.2446, -0.4658,  0.3446]])

Reshaping Tensors:
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])

Shows the y, z tensor:
tensor([ 0.9959,  0.4080, -0.7122,  2.5993, -0.1235, -1.9314, -0.2966, -2.2324,
        -0.2596, -0.2073,  0.3111, -0.5772, -1.3707, -1.2446, -0.4658,  0.3446])
tensor([[ 0.9959,  0.4080, -0.7122,  2.5993, -0.1235, -1.9314, -0.2966, -2.2324],
        [-0.2596, -0.2073,  0.3111, -0.5772, -1.3707, -1.2446, -0.4658,  0.3446]])


## Numpy

In [28]:
# Numpy
# Converting a Torch Tensor to a NumPy array
a = torch.ones(5)
print("Tensor Converted to NumPy Array:")
print(a)

# torch to numpy with .numpy()
b = a.numpy()
print("\nNumPy Array:")
print(b)

print("\nType of Converted Array:")
print(type(b))

Tensor Converted to NumPy Array:
tensor([1., 1., 1., 1., 1.])

NumPy Array:
[1. 1. 1. 1. 1.]

Type of Converted Array:
<class 'numpy.ndarray'>


## Memory and relations between Tensor and NumPy

In [29]:
# Careful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print("Modified Tensor (after adding 1):")
print(a)

print("\nCorresponding NumPy Array (also modified):")
print(b)

# numpy to torch with .from_numpy(x)
a = np.ones(1)
b = torch.from_numpy(a)
print("\nNumPy Array Converted to Tensor:")
print(a)
print(b)

# again be careful when modifying
a += 1
print("\nModified NumPy Array (after adding 1):")
print(a)

print("\nCorresponding Tensor (also modified):")
print(b)

Modified Tensor (after adding 1):
tensor([2., 2., 2., 2., 2.])

Corresponding NumPy Array (also modified):
[2. 2. 2. 2. 2.]

NumPy Array Converted to Tensor:
[1.]
tensor([1.], dtype=torch.float64)

Modified NumPy Array (after adding 1):
[2.]

Corresponding Tensor (also modified):
tensor([2.], dtype=torch.float64)


## CPU, GPU with tensor

In [35]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available)
if torch.cuda.is_available():
  device = torch.device("cuda")  # a CUDA device object
  print(device)
  y = torch.ines_like(x, device=device)  # directly create a tensor on GPU
  x = x.to(device)  # or just use strings .to("cuda")
  z = x + y
  print("Tensor on GPU:")
  print(z)

  # move to CPU again
  z.to("cpu")
  print("\nTensor on CPU:")
  print(z)

In [36]:
# Check cuda or apple silicon
print(torch.cuda.is_available())
print(torch.backends.mps.is_available())

False
False
