# Week 1 - Autograd PyTorch

In [1]:
# The autograd package provides automatic differentiation
# for all operations on Tensors
import torch

In [8]:
# requires_grad = True -> tracks all operations on the tensor
x = torch.randn(3, requires_grad=True)

print(x)

tensor([ 1.8321,  2.0750, -1.2427], requires_grad=True)


In [9]:
# Enable gradient tracking for tensor x
# x.requires_grad_(True)

# Define a new tensor y as a result of an operation on x
y = x + 2

# Since y is created as a result of an operation, it has a grad_fn attribute
# grad_fn references a Function that has created the tensoe
print(f"x -> {x}")  # created by the user -> grad_fn is None
print(f"y -> {y}")

# Perform more operations on y
z = y * y * 3
print(f"z -> {z}")

# Calculate the mean of z
z = z.mean()
print(f"z sum -> {z}")

# Perform backpropagation to compute the gradients
# When computation finishes, call .backward() to compute gradients automatically
# The gradient for this tensor wil be accumulates into .grad attribute
# It represents the partial derivative of the function with respect to the tensor
z.backward()
print(f"x grad -> {x.grad}")

# Detach tensor x from the computational graph to demonstrate example of accumulating gradient
x = x.detach()
print(x.detach())
print(f"Is gradient calculation required? {x.requires_grad}")
# Generally speaking, torch.autograd is engine for computing vector-Jacobian product
# It computes partial derivatives while applying the chain rule

x -> tensor([ 1.8321,  2.0750, -1.2427], requires_grad=True)
y -> tensor([3.8321, 4.0750, 0.7573], grad_fn=<AddBackward0>)
z -> tensor([44.0559, 49.8157,  1.7204], grad_fn=<MulBackward0>)
z sum -> 31.86400604248047
x grad -> tensor([7.6643, 8.1499, 1.5146])
tensor([ 1.8321,  2.0750, -1.2427])
Is gradient calculation required? False


In [10]:
# Create a tensor 'x' of shape (3,) with requires_grad set to Trye to enable gradient tracking
x = torch.randn(3, requires_grad=True)

# Perform a series of operations on 'x' to obtain tensor 'y'
# 'y' will have the same shape as 'x' and will contain the result of the operations
y = x * 2  # Multiply 'x' by 2
for _ in range(10):
  y = y * 2  # Multiply 'y' by repeatedly, resulting in a non-scalar output

# Print the tensor 'y' and its shape
print(y)
print(y.shape)

# Create a tensor 'v' representing the gradient with respect to 'y'
# This tensor specifies how much each element of 'y' contributes to the final gradient
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float32)

# Use backward() with an additional 'gradient' argument to compute gradients of non-scalar outputs
# 'v' acts as the gradient argument here, indicating the gradients that should be backpropagated
y.backward(v)

# Print the gradients of 'x' after backpropagation
print(x.grad)


tensor([-1188.9368,  1335.0835,   259.0704], grad_fn=<MulBackward0>)
torch.Size([3])
tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [12]:
# Check if requires_grad is enabled for tensor 'a'
a = torch.randn(2, 2)
print(a.requires_grad)

# Perform operations on tensor 'a' to create tensor 'b'
b = ((a * 2) / (a - 1))

# Print the gradient function of tensor 'b'
# Since 'b' is a result of operations on 'a', it will have a gradient function
print(b.grad_fn)

# Enable requires_grad for tensor 'a' using requires_grad_()
a.requires_grad_(True)
print(a.requires_grad)

# Perform operations on tensor 'a' to create tensor 'b'
b = (a * a).sum()

# Print the gradient function of tensor 'b'
# Since 'b' is a result of operations on 'a', it will have a gradient function
print(b.grad_fn)

# Detach tensor 'a' to create tensor 'b' without gradient computation
a = torch.randn(2, 2, requires_grad=True)
print(a.requires_grad)

b = a.detach()
print(b.requires_grad)

# Wrap the operation in 'with torch.no_grad()' to temporarily disable gradient tracking
a = torch.randn(2, 2, requires_grad=True)
print(a.requires_grad)
with torch.no_grad():
  print((a ** 2).requires_grad)

False
None
True
True
False
True
False


## Final expamle

In [ ]:
# Create a tensor 'weights' with requires_grad enabled for optimization
weights = torch.ones(4, requires_grad=True)

# Run training for multiple epochs
for epoch in range(3):
  # Just a dummy example: compute model output (sum of weights multiplied by 3)
  model_output = (weights * 3).sum()

  # Perform backpropagation to compute gradients
  model_output.backward()

  # Print the gradients of weights
  print(weights.grad)

  # Optimize the model by adjusting weights using gradient descent
  # Update weights using gradient descent formula: new_weights = old_weights - leraning_rate * gradient
  with torch.no_grad():
    weights -= 0.1 * weights.grad

  # Important step: Empty the gradients before the next optimization step to avoid accumulation
  weights.grad.zero_()

# After training, print the final weights and model output
print(weights)
print(model_output)

# Note: Optimizers provided by torch.optim automatically handle gradient updates and zeroing gradients
# Example usage:
# optimizer = torch.optim.SGD([weights], lr=0.1)
# During training loop:
# optimizer.step()  # Update weights based on gradients
# optimizer.zero_grad()  # Clear gradients for the next iteration